# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38a6fbe8d12c344630ca221843d410b30f09e67589026c2c2d1065f93fc3ecd246112de85343796dd360e65a58b061e9dac9d7ca7fbe4c0e7ea9891b96995a80

test:
  secret_key_base: 0dc711b0bd1d3883b10882b962b3572b1bdfa3ed55b6258718e1da419a5ba037352dc2376f87ffdcacea39d2e30cdbc14da18809decd01bd14e5c6aae5e5a30b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
